// <copyright file="Program.cs" company="PublicDomain.com">
//     CC0 1.0 Universal (CC0 1.0) - Public Domain Dedication
//     https://creativecommons.org/publicdomain/zero/1.0/legalcode
// </copyright>
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Windows.Forms;
using System.IO;
using System.Runtime.CompilerServices;
using System.Linq;

namespace DateTimeDirectory
{
    /// <summary>
    /// Class with program entry point.
    /// </summary>
    internal sealed class Program
    {
        /// <summary>
        /// Program entry point.
        /// </summary>
        [STAThread]
        private static void Main(string[] args)
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);

            // Check for args
            if (args.Length > 0)
            {
                // Try block with error message
                try
                {
                    // Set directory path
                    string directoryPath = args[0];

                    // Create DateTime directory 
                    Directory.CreateDirectory(Path.Combine(directoryPath, DateTime.Now.ToString("yyyy-MM-dd hh-mm-ss")));
                }
                catch (Exception ex)
                {
                    // Error, advise user
                    MessageBox.Show($"Error while creating DateTime directory. Message: {ex.Message}", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
            else
            {
                // Regular execution
                Application.Run(new MainForm());
            }
        }
    }
}